# Setup
title: Amol Vyawhare
tagline: Programming adventures
description: Notes and reference to future me
url: https://amolrv.github.io
paginate: 1
baseurl: ""
permalink: :title/
twitter:
  username: amol_vyawhare
  card: summary
kramdown:
    input: GFM
    footnote_backlink: "&#10548;"
# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

ga_analytics: UA-179175457-1

# Specify the author for blog posts
author:
  name: Amol Vyawhare
  url: https://twitter.com/amol_vyawhare
  email: amol.vyawhare@outlook.com

# Custom vars
version: 1.3.0
github:
  repo: https://github.com/amolrv/amolrv.github.io
