FROM mcr.microsoft.com/devcontainers/jekyll:bullseye

# Set environment variables for Jekyll
ENV TZ=Asia/Kolkata

# [Optional] Install additional OS packages if needed
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Install additional Ruby gems if needed
# RUN gem install <your-gem-names-here>

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
